### ISSUE TITLE
When clicking on Star book Community 

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/star_book#463] opened 2023-09-29 05:40 UTC
Here is a new link: https://discord.gg/7EJv8VUGrd

**Comment by gantanikhilraj** [comment] 2023-09-30 16:26
Hey @hashirshoaeb , I would to work on this issue, can you assign this to me and also give me some more details on this issue.

**Comment by hashirshoaeb** [comment] 2023-09-30 17:32
Done

**Comment by gantanikhilraj** [comment] 2023-09-30 17:37
@hashirshoaeb , Can you explain me the what the issue is about ?

**Comment by gantanikhilraj** [comment] 2023-10-01 06:15
I've submitted the PR, if any changes required please let me know.

**Closed** 2023-10-02 00:22 UTC
Labels: good first issue, hacktoberfest
